### ISSUE TITLE
Date parsing breaks with docker 1.6.1 on Debian Jessie

### ISSUE THREAD

**Issue by mpe** [spotify/docker-gc#29]
With `Docker version 1.6.1, build 97cd073`:

```
$ sudo docker-gc
date: invalid date ‘"2015-07-25 09:26:5’
/usr/sbin/docker-gc: line 69: 1438142405 - : syntax error: operand expected (error token is "- ")
```

Bash trace:

```
$ sudo bash -x ./docker-gc 
+ set -o nounset
+ set -o errexit
+ GRACE_PERIOD_SECONDS=3600
+ STATE_DIR=/var/lib/docker-gc
+ DOCKER=docker
+ EXCLUDE_FROM_GC=/etc/docker-gc-exclude
+ '[' '!' -f /etc/docker-gc-exclude ']'
+ EXCLUDE_FROM_GC=/dev/null
+ EXCLUDE_IDS_FILE=exclude_ids
+ '[' '!' -d /var/lib/docker-gc ']'
+ cd /var/lib/docker-gc
+ docker version
+ docker ps -a -q --no-trunc
+ sort
+ uniq
+ docker ps -q --no-trunc
+ sort
+ uniq
+ compute_exclude_ids
+ PROCESSED_EXCLUDES=processed_excludes.tmp
+ sed 's/^\(.*\)$/ \1 /' /dev/null
+ sed '/^ *$/d'
+ docker images
+ tail -n+2
+ sed 's/^\([^ ]*\) *\([^ ]*\) *\([^ ]*\).*/ \1:\2 \3 /'
+ grep -f processed_excludes.tmp
+ cut '-d ' -f3
+ sed 's/^/^/'
+ comm -23 containers.all containers.running
+ echo -n ''
+ cat containers.exited
+ read line
++ docker inspect -f '{{json .State.FinishedAt}}' 16e1b23066c2462a70fd9c027a4e85a7ed0828f306c694c5ffec36d7c7160021
+ EXITED='"2015-07-25T09:26:54.517387651Z"'
++ elapsed_time '"2015-07-25T09:26:54.517387651Z"'
+++ date -u +%s
++ utcnow=1438143000
++ without_ms='"2015-07-25T09:26:5'
++ replace_t='"2015-07-25 09:26:5'
+++ date_parse '"2015-07-25 09:26:5'
+++ date --utc
++++ date -u --date '"2015-07-25 09:26:5' +%s
date: invalid date ‘"2015-07-25 09:26:5’
+++ echo
++ epoch=
./docker-gc: line 69: 1438143000 - : syntax error: operand expected (error token is "- ")
+ ELAPSED=
 $ 
```

It looks like the inspect returns surrounding quotes which are confusing the without_ms logic:

```
$ t=$(docker inspect -f '{{json .State.FinishedAt}}' 16e1b23066c2462a70fd9c027a4e85a7ed0828f306c694c5ffec36d7c7160021)
$ echo $t
"2015-07-25T09:26:54.517387651Z"
$ echo ${t:0:19}
"2015-07-25T09:26:5
```

**Comment by xealot** [comment]
This is present in 1.7 also

**Comment by sheldonkwok** [comment]
date parses the string correctly if you just remove the quotes without slicing the return

**Comment by xealot** [comment]
You're right, it's more compatible too. Changed to use code similar to your suggestion.
https://github.com/ihr-radioedit/docker-gc/pull/2

**Comment by mbruggmann** [comment]
@daenney can you have a look at this? This probably broke with your patch regarding date parsing.

**Comment by sheldonkwok** [comment]
I can confirm that my docker-gc works correctly now after correctly parsing the " in the string. I'm running docker 1.7 on Ubuntu 14.04

**Comment by daenney** [comment]
I can have a look at it tomorrow but I didn't run into this issue on both my Mac and my Ubuntu Trusty machine that I tried this on so I'm curious why this suddenly showed up.

**Comment by daenney** [comment]
@xealot Do you think you could be helpful here and raise this as a PR?

**Comment by sheldonkwok** [comment]
What version of docker are you running @daenney

**Comment by kerphi** [comment]
Same problem here :

```
kerphi@p-gully:~$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock spotify/docker-gc
date: invalid date '"2015-07-09 20:05:3'
/docker-gc: line 69: 1438670724 - : syntax error: operand expected (error token is "- ")
```

My OS and my Docker version :
```
kerphi@p-gully:~$ cat /etc/debian_version 
8.1
kerphi@p-gully:~$ docker -v
Docker version 1.7.1, build 786b29d
```

**Comment by daenney** [comment]
#31 should fix it.

**Comment by kerphi** [comment]
Is it fixed in the docker image of docker-gc ?

**Comment by daenney** [comment]
Considering the PR isn't fixed, no. But I don't think we rebuilt the image yet with the previous change since we didn't tag a release so the container itself should be unaffected.

**Comment by aidanhs** [comment]
Well there are no tags at all on this repo (:cry:) and the auto image build rebuilds on every commit. Once this is fixed it would be nice to get at least one tagged image!

**Comment by aidanhs** [comment]
Any change of a tag now?
